
version: '3.8'

services:
  rabbitmq:
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  postgres:
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  mongo:
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  redis:
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 256M

  zipkin:
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 256M

  prometheus:
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 256M

  grafana:
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 256M

  influxdb:
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 256M

  elasticsearch:
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M

  logstash:
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  kibana:
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 2048M

  zookeeper:
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 512M

  kafka:
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1024M

  scylla:
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M
